#!/bin/bash
# -*- Mode: sh; coding: utf-8; indent-tabs-mode: nil; tab-width: 4 -*-
#
# Authors:
#   Sam Hewitt <hewittsamuel@gmail.com>
#
# Description:
#   An uninstallation bash script for Moka Icon Theme
#
# Legal Stuff:
#
# This file is part of the Moka Icon Theme and is free software; you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation; version 3.
#
# This file is part of the Moka Icon Theme and is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License along with
# this program; if not, see <https://www.gnu.org/licenses/gpl-3.0.txt>

ROOT_UID=0
if [ "$UID" -ne "$ROOT_UID" ]
then
	echo "Moka Icon Theme will be removed from '$HOME/.icons'. To make them available for all users, run this script as root."
else
	echo "Moka Icon Theme will be removed from '/usr/share/icons' and will be available for all users."
fi
read -p "Do you want to continue ? [Y]es, [N]o : " input
case $input in
	[Yy]* ) ;;
    [Nn]* ) exit 99;;
    * ) echo "Uh oh, invalid response. Installaton aborted."; exit 1;;
esac

if [ "$UID" -eq "$ROOT_UID" ]
then
	rm -Rf /usr/share/icons/Moka 2>/dev/null
else
	rm -Rf $HOME/.icons/Moka 2>/dev/null
fi

echo
echo "Uninstal complete! Exiting"
exit 0